schema_version = "1.0.0"

id = "replace_selected_with_active"
version = "3.0.0"
name = "Replace Selected with Active"
tagline = "Replace selected objects with copies of the active object"
maintainer = "Taiyo"
type = "add-on"
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]

[build]
paths_exclude_pattern = [
  "__pycache__/",
  ".*",
  "*.zip",
]
