schema_version = "1.0.0"

id = "modular_asset_renamer"
version = "1.0.7"
name = "Modular Asset Renamer"
tagline = "Build and apply modular names to selected assets"
maintainer = "Taiyo"
type = "add-on"
blender_version_min = "4.5.0"
website = "https://github.com/Taiyo1031/taiyo-blender-scripts/blob/main/_Taiyo_Blender_Extensions_Repo/modular_asset_renamer/README.md"
license = ["SPDX:GPL-3.0-or-later"]
tags = ["Object", "Scene", "Pipeline"]

[build]
paths_exclude_pattern = [
  "__pycache__/",
  ".*",
  "*.zip",
]
