schema_version = "1.0.0"

id = "taiyo_extension_manager"
version = "1.0.9"
name = "Taiyo Extension Manager"
tagline = "Search, install, update, and uninstall Taiyo Extensions"
maintainer = "Taiyo"
type = "add-on"
blender_version_min = "4.2.0"
website = "https://github.com/Taiyo1031/taiyo-blender-scripts/blob/main/_Taiyo_Blender_Extensions_Repo/taiyo_extension_manager/README.md"
license = ["SPDX:GPL-3.0-or-later"]

[build]
paths_exclude_pattern = [
  "__pycache__/",
  ".*",
  "*.zip",
]
