schema_version = "1.0.0"

id = "laid_collection_instance_linker"
version = "1.0.1"
name = "CW_Laid Collection Instance Linker"
tagline = "Rebuild laid maps with matched collection instances"
maintainer = "Taiyo"
type = "add-on"
blender_version_min = "4.2.0"
website = "https://github.com/Taiyo1031/taiyo-blender-scripts/blob/main/_Taiyo_Blender_Extensions_Repo/laid_collection_instance_linker/README.md"
license = ["SPDX:GPL-3.0-or-later"]
tags = ["Object", "Scene", "Pipeline"]

[build]
paths_exclude_pattern = [
  "__pycache__/",
  ".*",
  "*.zip",
]
