schema_version = "1.0.0"

id = "blend_reference_graph"
version = "0.1.1"
name = "Blend Reference Graph"
tagline = "View Blender reference graphs in HTML"
maintainer = "Taiyo"
type = "add-on"
blender_version_min = "4.2.0"
website = "https://github.com/Taiyo1031/taiyo-blender-scripts/blob/main/_Taiyo_Blender_Extensions_Repo/blend_reference_graph/README.md"
license = ["SPDX:GPL-3.0-or-later"]
tags = ["Object", "Scene", "Pipeline"]

[build]
paths_exclude_pattern = [
  "__pycache__/",
  ".*",
  "*.zip",
]
